[[Ccache]]
arch = "aarch64"
git-tree-sha1 = "d02b6e2de152a63f97a0e987537ff9e386f903c5"
os = "macos"

    [[Ccache.download]]
    sha256 = "bbd9535e4959f21ac295c6db15ca60e7b440d505ba4356d104270aafba04c888"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.aarch64-apple-darwin.tar.gz"
[[Ccache]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31aa2c4ca9466307ec87499ed3aef6b7de02295e"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "1be64492bdc47af3dbb7e4440f1dbfc3ffb86f1c78bfe0886872c75d66f4e2c0"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.aarch64-linux-gnu-cxx03.tar.gz"
[[Ccache]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "995fb1cd827d3d8fab1a133896fcfdeba19c9ada"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "734e7d41946b4e868ed1ee559d99c8b667bc8cd1825b1ef754460c29647a0430"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.aarch64-linux-gnu-cxx11.tar.gz"
[[Ccache]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87fd92de2a4d5648db9c3286597dacd885d114a4"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "635c5c22583be0ec69ca8e63355b1b986b653e99a6f188d18fe2465bedff89e2"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.aarch64-linux-musl-cxx03.tar.gz"
[[Ccache]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2dde2a8e566e8d5a5ea75e21d95f04ea2aea26c"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "ab24948fba6579d815054573622192a259fb71079daf6f870d92a133c3592898"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.aarch64-linux-musl-cxx11.tar.gz"
[[Ccache]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5141147d8a6d5786990acc76924292440a8424b6"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "11a2190b3399f832628a1b3db13d1fdbd0f5801edafbe506237cf71051bc6ac1"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Ccache]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c60f114eb4aee106ad49f08cf97bdd5fbfb2f6fa"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "51993f1b828030483c8f8eef8862a406c292bfbd9ae118a914d8265a74bbe813"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Ccache]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9eafd14f503e16b80c7d0e6cea6dd07652f3ab46"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "013f02a2572bc002137cebf86fc1de6a156cd3537f7b5384dbb95e5713b5a623"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Ccache]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bccf2910ba29fbc372accc0dc28c72bdfcea06d"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "e49cee47180262e583ff4b635a5675a2e9f533fe338d8820b9e2bffde1fa5190"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Ccache]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1120ea2b35badb5538982925aca51a2c9ea1df86"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "947c06eeb36147e2c9a848f640079a6690ebd6e87ebecf4c575eba92f35e5461"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Ccache]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "646dc7d044721b29f7ceb7acbd899158d4f6dc6f"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "a731176c440d58bdb07d1bd99630195f5e76602c91543d67c1b247f9d5f99477"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Ccache]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53786cb4d2b4d74de3b2e61a30a47917725dbf5d"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "e877a128a5f8f99c579a1549abe4666f6f5c9c8f24cd586535ccc8fdadc96647"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Ccache]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d08041a1e8341dda46aeb40c7f844f476229b062"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "ab3dcb1429abcd12b9f0ffdb90aed28e6aecb2ebb8cfdcb45677a3f452619bc1"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "558a59de26369cedd3189589d8c22fe6214ca120"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "e1f67d18eb9e4c9a6d2ef4880d6458e8ebd7870c89ad53a1869519a2ca44e9ce"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.i686-linux-gnu-cxx03.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c676485046b2167938c9853bae104318fea471ff"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "3ce1e223095197df2fabaf3c0f29a05e9701b37bb03effeb08aaeda52402e745"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.i686-linux-gnu-cxx11.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7fb95f459a9d3def06c73df58a8bb93cda4bd7d"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "4c0b9804d2c798942e8d9e32806397032277f47b6d32d1bc2763cb0259eaf2fa"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.i686-linux-musl-cxx03.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "291b20e0ae098dec4a960f9416417680bde8bb32"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "fa48b65db3576c09e9d8e83bb05676aeddb76e5c811d6d7363b53e1d53412f62"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.i686-linux-musl-cxx11.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec85f746f14a2e65ffc8756b8b06996dd7b192c3"
os = "windows"

    [[Ccache.download]]
    sha256 = "fe06b5977f83ff9d0e096448bc22349780743742613d6f831cec4bae32547830"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.i686-w64-mingw32-cxx03.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60172af438496f5cbecbe0a52787033972a6cd33"
os = "windows"

    [[Ccache.download]]
    sha256 = "d529523af316aa408a6fe9dde6f8a96f837b27a9b4a0f93132ba9c2febea42d8"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.i686-w64-mingw32-cxx11.tar.gz"
[[Ccache]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed3afc1e34b781105371bf0fec722837143cdd5e"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "7def881359790cc73a8a360c8885236703ec6c9c2d4a51d4f08148bbf9577021"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Ccache]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb87f0e0c56025ee253af2bda89803693ab6718e"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "e511dc993e44588082b7743c7596e2aa963a03dd92cd3e25dc0cac6ec722b211"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Ccache]]
arch = "x86_64"
git-tree-sha1 = "6749c9848a9782c9e3ee1bb5c4bfc336dc369468"
os = "macos"

    [[Ccache.download]]
    sha256 = "d82b5fd3210537a0402824693878e606942dc8db8f42fdb93a448130b27db79b"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.x86_64-apple-darwin.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45e8e76e7dd6cd8fca4ca6aaba9f328612006494"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "a7f3b482f1b315f8602d2e09038885f6cde0fa759af2c7f3e715d36333c55d29"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.x86_64-linux-gnu-cxx03.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec641755fbbabc10f4797e1bf7c0c63aea31ba77"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "2e28ca838a2cffd8bf501e7a56e92916907fd927a4ef2c955ad352802a9a20f9"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.x86_64-linux-gnu-cxx11.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb0d723cebe959ce8f1bdeea92d6dd507c780f50"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "17704d850080d3a227af420bdc90cd89b440d4c013e6b977fc1dc0cce1f04b67"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.x86_64-linux-musl-cxx03.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8de7a3a4081d1fc3edd88ec586c68f53878fa2d"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "62ef29e077a0ac085fdfbbea530dbd91f8d6162f90ad71e52c48621a91021fd2"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.x86_64-linux-musl-cxx11.tar.gz"
[[Ccache]]
arch = "x86_64"
git-tree-sha1 = "d54cb9537ce1711bd58ad5e55c3328bacbfa5ad7"
os = "freebsd"

    [[Ccache.download]]
    sha256 = "b565b0c87ccf43f5bbe62394e6f1836baa98b56450e3a817d37646fc7fed6402"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.x86_64-unknown-freebsd.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80bf127e87204ea8d2a32a00b15f11feabaeb7ad"
os = "windows"

    [[Ccache.download]]
    sha256 = "627dcf11426bc355dadbf7dc7de05b3f9bf0923ef2fa0a5210a5d3636e3c2cb4"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "010c1f46b4fc3d5212c9e6f971c9586e59f97655"
os = "windows"

    [[Ccache.download]]
    sha256 = "362cee73e361e2b0575264c8aba09ddbacaad902dc1e28fff20a06c1d61b1d3b"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.7.4+0/Ccache.v4.7.4.x86_64-w64-mingw32-cxx11.tar.gz"
