[[Ccache]]
arch = "aarch64"
git-tree-sha1 = "ee37ddaef91c983ab8381c1c9e5dbd03c8af4654"
os = "macos"

    [[Ccache.download]]
    sha256 = "886726c41ccc409b550c3e2691c9c3c9ebb21bc8d4d192b5d3aeb410c20429a3"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.aarch64-apple-darwin.tar.gz"
[[Ccache]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78a3de3a8d6175f57ba9992cdf207c662397ba10"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "e2d902536909457b06e240362fdedd9195d975c391d174046dc25f7a2099e487"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Ccache]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ec1464f87d7a6ccb0e7af2e9a03e0cf81849e1a"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "8071adf8437557820f2c3043bfce90b7fe7804ab0c0bd413d3546b835aa6790a"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Ccache]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "220bbc2e50eff82efe0f3f055277690281adf016"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "06cc89501e971b5ee809fd9214f3557019c6bcdfaafa8374e4a1729c7f12db12"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.aarch64-linux-musl-cxx03.tar.gz"
[[Ccache]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb3d75c87395c07d0cda82a5fed4cb3c9c1a77e4"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "85a7d7e1612835d10486beee9fb9c2e4432401fdf0489719e6c4371f10eee73e"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.aarch64-linux-musl-cxx11.tar.gz"
[[Ccache]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1c147e52b484b243b05940245f110d9b2eec6c9"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "db5229541b5800929bfb9e7a4a8dbc8efaf6963dd7876de33b3477efe7ce190a"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Ccache]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e9ae76b514be1c661f3671f7c469553ff487a1c"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "39c99f27df84b8a54054a7fca09559059f026f94e4b63b4d3cfe05c09d905e17"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Ccache]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2849ad3f617f197fa13da3c04275171d15bc5c62"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "d60e5b5b5f3d3c2d994429f7934ae75533d3156e7a6a2dd7e2e26b9624eb5ee8"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Ccache]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92c2b69bcc00878dc77ab664517ead4084c3c094"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "243285c32fdf14dfc7264aa1fc37a8f4cbdb6840148e12dbbff6905d5cc3bac7"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Ccache]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d2b1d8d1026d0aacaafab80e43de852ff33c181"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "dc7991559db7db0196e1c33f0fc60d456ac491b63e070593bca42509c9f98265"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Ccache]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40782e053734a06e37db25629bbbf22f93b74f0a"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "b802a2c2b57a8815ad346b224d790d3e597466233ae98243db4d007098c7b16e"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Ccache]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "053cf442bff688c9aaabd1784f9c8dc75fd6aa1b"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "d16f09bfc4997463eff45202918ca571cbc23e052ca5fd0f5eb47642a364414a"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Ccache]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c007b6b49ea99b9c547ac9ae67c68cccb9abc930"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "771709ea9bfc407b6b41ac566d510f595c4d37c256db7aa2cfa652873f8775c1"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41be958fc7af6de6606f47e1d7a4ae296e967e83"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "84f6ccea2f78714901373197e0761affb081ad14f4228632b90ee9962c4b5d70"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.i686-linux-gnu-cxx03.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "526dc8e64ea3b27c1219a7095884ca1523abd3f2"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "8f1f4937c6034123b0dedbf902d662347dbd529ee17f9fee241d51f60bf28a01"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.i686-linux-gnu-cxx11.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7f9db028899928faba52ec702d3a84dbafad303"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "f522df7fc8e51dac610003b33929bb021233b0d8804b971f7306e5e3e17b62d8"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.i686-linux-musl-cxx03.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef50c77e836c90500a6b74cbe603f3d9411692c1"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "ff52b7048417631f010b45f6c94618125ad6226ead707626829c5d12028cb144"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.i686-linux-musl-cxx11.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcbc3b8c9a8987195cc67e1405004981dd7753cd"
os = "windows"

    [[Ccache.download]]
    sha256 = "06dfec8a860e8fe23fbcd4ad30ade480c23c3a78186495d307e6ce92be9b2091"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.i686-w64-mingw32-cxx03.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12fef8fdc1acb0f740245db5d73243d5a00bedae"
os = "windows"

    [[Ccache.download]]
    sha256 = "015e616ec179d4b9a08a4b74f604f26773cea11fa8283cab993ca0b70ecddadd"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.i686-w64-mingw32-cxx11.tar.gz"
[[Ccache]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b952307aa5517f4bbc073b1f254f99c4fb9a3458"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "b2ac37131cfaa2dc62bcafef8447ba0e500c579ff0ebcfe96434514cc97d83d8"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Ccache]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18da1d344b4070f555b37650cb3b3e229090b122"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "f0b38e65b90a41aeab4a513989bd8af0f2726f1f3663ac3ab81fcc219616654f"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Ccache]]
arch = "x86_64"
git-tree-sha1 = "48c78577d86181d0e4c0087cb54affedc18bf36a"
os = "macos"

    [[Ccache.download]]
    sha256 = "3fe0f619a2136e92508f07f6560ac70b7888293838754ed862a3114c0e761527"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.x86_64-apple-darwin.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6f1db63f3bce6274b9c70eae6b91aa89a407501"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "b41342e4e9525bd165565bc149c410040eb01fea0b13d5336b08c307df762f6b"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e81e7a81695d66d1c3c20b1e885f9da25c6e3b53"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "5b946c882290fed32fed3acf4fe6b49b6b44ff627ecd7f5338ba963d28facbdc"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49ea202a16e1f594491dbd0e3319c5ea6764a975"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "56e7970b4fcaf02eba1c0cc249266422afa4d656ba18076668bf56aae9f9ee7a"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.x86_64-linux-musl-cxx03.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74de61eab4a7a32c02ff41a04ac63a4e5411beaf"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "9a071aca3a63407acc401afb6ca99ad6ebd8f8ec7397301a46bff1b82d18a90b"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.x86_64-linux-musl-cxx11.tar.gz"
[[Ccache]]
arch = "x86_64"
git-tree-sha1 = "3d0d9004717c2c562bed31456bd12898211183d2"
os = "freebsd"

    [[Ccache.download]]
    sha256 = "850fa20e49a13183bbc47bd60fa48c4b484e26fb6d5e60b6479b52433172dd7b"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.x86_64-unknown-freebsd.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e8717b010d5a41617014eaf374617f49d172d79"
os = "windows"

    [[Ccache.download]]
    sha256 = "e830b13a26ba0ca88bb648049e6916669f7fec197f52f60df5a129fa25fb66e1"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cecc1aec2c40a3f12eb4c5fa018d02a439b29a8c"
os = "windows"

    [[Ccache.download]]
    sha256 = "a5ef0e872ecf7af6e635495eeb8807597b5bdddba00f816caaefc1a821829a6d"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.9.1+0/Ccache.v4.9.1.x86_64-w64-mingw32-cxx11.tar.gz"
