[[Ccache]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0665346337daddafb9d760853ed2754d84b9829"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "705d14b1f11bb057445e1c3ac8ad09951e8af0885330893d90cfb4322d56696a"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Ccache]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "001f03899034aae377298a0d0137018feeb17cf8"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "f96e4a4ef86859bd2a6f598f7d32ce187b83dbf14a547f3e5c26ba69b071316d"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Ccache]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13a6ea86011fe98cab765734226ea8f662904a65"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "c154c4f7f63d6d6bcab83fc237d74c0e881b670460018f53923cac0804b44cfc"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[Ccache]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e6118dcf1f63380294a09e17630ab59da4d32e5"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "28657fd1b1e1dfa642348225d818b7944dee94dd9f50029609c680ab2824f243"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[Ccache]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "538a703f921f4d29d119d73c9bb87b0640bf6025"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "c1cf78d368b0d01b26636a8f80406d5de60cf9e6daee3663fe7852b33e400e8b"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Ccache]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53f3f8c79c099215d1146600b707008194d8728a"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "0175fca0c8a8ab4661c254dd32c1b9c65cefb9dd5038bde68b521b13f03c9147"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Ccache]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "671acedde9a78abc57fbf3c4d2a4ba651c8a5cec"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "fb199aa954d993b5d392bf4eda71ed54935bd0e0ce80977e5de2ab9c44cf7c9a"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Ccache]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "107f204795898467878bf168431a1022887ea06e"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "b820b81ed2603e11b5fd5bde1a5de7817a0ef3dc6c27b68be29628d5523bdcb1"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dcb8cb1c05586a9a8befa9fbedfc800c888636e3"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "b2032b323caf032e9c432a2932a1f409b1002eb5031ef8205108aef17f22c07e"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.i686-linux-gnu-cxx03.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c61a7ee512ed862851129f8519a3182741b5255"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "41f51a2d1e6b2eb4b8931683625f0c0b9796d820f7786305c39ac9b005ed6c6e"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.i686-linux-gnu-cxx11.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "544015abf5b077f80584276c8d30b7cc86334b97"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "93cbece9e0db48a5bbb50c818cb371d8e4aa18d12848773d8de756e452984a81"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.i686-linux-musl-cxx03.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44f534c879bf7043e28b40c9e31fbe328aef8c15"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "d4af35fd422555745db4144883e3fde01c8d12b6d8850326bf61bae2c50129a1"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.i686-linux-musl-cxx11.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d313f0490c72456fab7b370b8129bddb6582edf"
os = "windows"

    [[Ccache.download]]
    sha256 = "20f62eab4d4dee1474ed20954ea25ced72d5d726d95539e2c35e97f90ccccf40"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[Ccache]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f7feb81c6a6c898572dec068eb753af76d7637e"
os = "windows"

    [[Ccache.download]]
    sha256 = "4b22b058fb92bebaab5fdf063235d37687272d75b87422585790b307626ee6bc"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[Ccache]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99d9613d512dd433ebb0e6ee39957c97ee74587d"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "6b4590964927963ebe3d8ac1f595df07762730f628b2699c60bcce49191e8e35"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Ccache]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d511403d646d88581a2053c21415cefe0dad2874"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "13b41153eb7cf74365cd329f076f7a52c0b66289ea31e00fc1f6ad37ad23d2a9"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Ccache]]
arch = "x86_64"
git-tree-sha1 = "dfcf6f56e6ce97bac89817642a84caf53d7c7393"
os = "macos"

    [[Ccache.download]]
    sha256 = "82e20f0b2ec69ab9a0375f2f7ee530d0625564b5ed6f2fa126ae3fb09d1a04e0"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.x86_64-apple-darwin.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cec8fdc4155f88870fc586574e976090ab70fde9"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "e2b2e849c8bc05f0031131a886965ab90ddcd07c71b09fe126bcf3e80f9ffcf5"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cac5f47a9528405681b2d66c76099778300ace1"
libc = "glibc"
os = "linux"

    [[Ccache.download]]
    sha256 = "34f9df3fd70322b896594828a4b4d4131c5532669a6b1dfbbbbdcbbe8e1e79b7"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e147d00ca93c2bedaed0717f72356da08ba1880d"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "9c46892e75a1b4324541626b14f7fc7beab2499a27e51fbe443940887c9d9590"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbb8d8d09eb0db540a48c7302784f187ac12bbfc"
libc = "musl"
os = "linux"

    [[Ccache.download]]
    sha256 = "c80422c16ce316fb7e6f3cab124c3f055e65ef9c7e5a4a2a599af45b765434ce"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[Ccache]]
arch = "x86_64"
git-tree-sha1 = "799af99967483ab4cd8d0d1d5cf05447862b30e9"
os = "freebsd"

    [[Ccache.download]]
    sha256 = "e2a8a13cc50628e5bae9211107605da5d138dbccb970ba7e48b8fdc8ac44dfeb"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.x86_64-unknown-freebsd.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc511de131c872c966e341cdd317336e1b30d58f"
os = "windows"

    [[Ccache.download]]
    sha256 = "8e9ee4c4722d2749a7fa3b7eee8314f145b7f10070501b817023127435e25283"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Ccache]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8dd988f7e2d0c154369726911dce9c87b21e1843"
os = "windows"

    [[Ccache.download]]
    sha256 = "ca628cbfe19b11ba6219a98243fca228b86778c51681bc4f175ee48f27f94162"
    url = "https://github.com/JuliaBinaryWrappers/Ccache_jll.jl/releases/download/Ccache-v4.2.0+0/Ccache.v4.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
